language: c
os:
 - osx

warnings_are_errors: false

before_install:
 - brew update
 - brew tap homebrew/science
 - brew install homebrew/science/Elemental --HEAD
 - brew --prefix homebrew/science/Elemental
 


 